"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const lab4_js_1 = require("./lab4.js");
var DocType = lab4_js_1.Transport.DocType;
var BodyType = lab4_js_1.Transport.BodyType;
var CarClass = lab4_js_1.Transport.CarClass;
var Owner = lab4_js_1.Transport.Owner;
var Car = lab4_js_1.Transport.Car;
var Motorbike = lab4_js_1.Transport.Motorbike;
var VehicleStorage = lab4_js_1.Transport.VehicleStorage;
const owner = new Owner("Гослинг", "Райан", "Драйвович", new Date(1990, 1, 2), DocType.Passport, "1234", "567890");
const car = new Car("Chevy", "Malibu", 1973, "1H57K3R460826", "A123BC", owner, BodyType.Sedan, CarClass.Comfort);
const motorbike = new Motorbike("Kawasaki", "H2R", 2025, "WAUZZZFY2M2061887", "D456EF", owner, "Сталь", true);
const vehicleStorage = new VehicleStorage();
vehicleStorage.save(car);
vehicleStorage.save(motorbike);
console.log(owner.printOwnerInfo());
console.log(car.printVehicleInfo());
console.log(motorbike.printVehicleInfo());
vehicleStorage.getAll().forEach(vehicle => console.log(vehicle.printVehicleInfo()));
